###
POST http://localhost:8080/api/v1/auth/sign-in
Content-Type: application/json

{
  "username": "janedoe",
  "password": "password"
}


###
POST http://localhost:8080/api/v1/auth/refresh-token
Content-Type: application/json

{
  "refreshToken": "59e6a616-8535-42ba-b119-d0c74b40acd4"
}
###

GET http://localhost:8080/api/test/user
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkYW1taSIsImlhdCI6MTY5MDcxNTA4OCwiZXhwIjoxNjkwNzE1Mzg4fQ.o42W1ZLUSQkc9visGE_uH4xxecRRMDvrGbKrH3bzc0E

###

GET http://localhost:8080/api/test/user
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqYW5lZG9lIiwiaWF0IjoxNjkwNTYyMzk3LCJleHAiOjE2OTA1NjI2OTd9.u1RCIrJOlfBrOlm7Z-jPpNMFIz9NWoJpYbg_hxTf0GA
###

POST http://localhost:8080/api/v1/auth/sign-up
Content-Type: application/json

{
  "userFirstName": "Damm",
  "userLastName": "Vega",
  "phone": "1234567890",
  "addressLine1": "123 Main Street",
  "addressLine2": "Apt 4",
  "city": "Example City",
  "state": "Example State",
  "postalCode": 123455,
  "country": "Example Country",
  "username": "dammi",
  "email": "dammi@example.com",
  "password": "password"
}
